defmodule Resolver.IntegrationTest do
  use Resolver.Case, async: true
  use ExUnitProperties

  alias Resolver.Registry.Process, as: Registry

  @moduletag :integration

  # ERRORS TO FIX
  # :timeout
  # broen 2.2.3
  # ejabberd 17.11.0
  # kyu 1.2.1
  # amqp_director 1.1.1
  # ami 0.1.4
  # ami_models 0.1.0
  # bypass 2.0.0

  # other
  # peluquero 0.99.8

  @expected_failures [
    {"achlys", "0.1.0"},
    {"achlys", "0.1.1"},
    {"achlys", "0.1.10"},
    {"achlys", "0.1.3"},
    {"achlys", "0.1.6"},
    {"achlys", "0.1.7"},
    {"achlys", "0.1.9"},
    {"achlys", "0.2.0"},
    {"beamoji", "0.1.0"},
    {"brucke", "1.15.0"},
    {"brucke", "1.15.1"},
    {"brucke", "1.15.2"},
    {"brucke", "1.16.0"},
    {"brucke", "1.16.1"},
    {"brucke", "1.17.0"},
    {"brucke", "1.17.1"},
    {"brucke", "1.17.2"},
    {"brucke", "1.17.3"},
    {"cloudi_service_oauth1", "1.5.1"},
    {"cowboy_oauth", "0.2.12"},
    {"cowboy_oauth", "0.2.13"},
    {"cowboy_oauth", "0.2.14"},
    {"cowboy_swagger", "0.1.1"},
    {"cowboy_swagger", "2.2.0"},
    {"cowboy_swagger", "2.2.1"},
    {"cowboy_swagger", "2.2.2"},
    {"cowboy_swagger", "2.3.0"},
    {"cowboy_swagger", "2.4.0"},
    {"cowboy_swagger", "2.5.0"},
    {"ddb_client", "0.1.14"},
    {"ddb_client", "0.1.15"},
    {"diint_utilites_common_app", "1.0.1"},
    {"diint_utilites_common_app", "1.0.10"},
    {"diint_utilites_common_app", "1.0.11"},
    {"diint_utilites_common_app", "1.0.12"},
    {"diint_utilites_common_app", "1.0.13"},
    {"diint_utilites_common_app", "1.0.2"},
    {"diint_utilites_common_app", "1.0.3"},
    {"diint_utilites_common_app", "1.0.4"},
    {"diint_utilites_common_app", "1.0.5"},
    {"diint_utilites_common_app", "1.0.6"},
    {"diint_utilites_common_app", "1.0.7"},
    {"diint_utilites_common_app", "1.0.8"},
    {"diint_utilites_common_app", "1.0.9"},
    {"diint_utilites_common_app", "1.1.0"},
    {"diint_utilites_common_app", "1.1.1"},
    {"diint_utilites_common_app", "1.1.2"},
    {"diint_utilites_common_app", "1.1.3"},
    {"diint_utilites_common_app", "1.1.4"},
    {"diint_utilites_common_app", "1.1.5"},
    {"diint_utilites_common_app", "1.1.6"},
    {"diint_utilites_common_app", "1.1.7"},
    {"diint_utilites_common_app", "1.2.0"},
    {"diint_utilites_common_app", "1.2.1"},
    {"diint_utilites_common_app", "1.2.10"},
    {"diint_utilites_common_app", "1.2.101"},
    {"diint_utilites_common_app", "1.2.11"},
    {"diint_utilites_common_app", "1.2.2"},
    {"diint_utilites_common_app", "1.2.3"},
    {"diint_utilites_common_app", "1.2.4"},
    {"diint_utilites_common_app", "1.2.5"},
    {"diint_utilites_common_app", "1.2.6"},
    {"diint_utilites_common_app", "1.2.7"},
    {"diint_utilites_common_app", "1.2.8"},
    {"diint_utilites_common_app", "1.2.9"},
    {"diint_utilites_common_app", "1.3.0"},
    {"diint_utilites_common_app", "1.3.1"},
    {"diint_utilites_common_app", "1.3.2"},
    {"diint_utilites_common_app", "1.3.3"},
    {"diint_utilites_common_app", "1.3.4"},
    {"diint_utilites_common_app", "1.3.5"},
    {"diint_utilites_common_app", "1.3.6"},
    {"diint_utilites_common_app", "1.3.7"},
    {"diint_utilites_common_app", "1.3.8"},
    {"diint_utilites_common_app", "1.3.9"},
    {"diint_utilites_common_app", "1.4.0"},
    {"diint_utilites_common_app", "1.4.1"},
    {"diint_utilites_common_app", "1.4.10"},
    {"diint_utilites_common_app", "1.4.11"},
    {"diint_utilites_common_app", "1.4.12"},
    {"diint_utilites_common_app", "1.4.14"},
    {"diint_utilites_common_app", "1.4.15"},
    {"diint_utilites_common_app", "1.4.16"},
    {"diint_utilites_common_app", "1.4.17"},
    {"diint_utilites_common_app", "1.4.18"},
    {"diint_utilites_common_app", "1.4.19"},
    {"diint_utilites_common_app", "1.4.2"},
    {"diint_utilites_common_app", "1.4.20"},
    {"diint_utilites_common_app", "1.4.21"},
    {"diint_utilites_common_app", "1.4.22"},
    {"diint_utilites_common_app", "1.4.23"},
    {"diint_utilites_common_app", "1.4.3"},
    {"diint_utilites_common_app", "1.4.4"},
    {"diint_utilites_common_app", "1.4.5"},
    {"diint_utilites_common_app", "1.4.6"},
    {"diint_utilites_common_app", "1.4.7"},
    {"diint_utilites_common_app", "1.4.8"},
    {"diint_utilites_common_app", "1.4.9"},
    {"dqe", "0.1.33"},
    {"egithub", "0.1.18"},
    {"egithub", "0.1.19"},
    {"elvis", "0.2.6-alpha3"},
    {"evaluator", "0.1.0"},
    {"exometer_influxdb", "0.6.0"},
    {"folsom_ddb", "0.1.18"},
    {"gleam_crypto", "0.1.0"},
    {"gleam_crypto", "0.1.1"},
    {"gleam_jsone", "0.4.0"},
    {"gleam_sentry", "0.1.0"},
    {"gleam_sentry", "0.1.1"},
    {"gleam_synapses", "0.0.1"},
    {"hexer", "0.0.1"},
    {"hexer", "0.1.0"},
    {"hexer", "0.2.0"},
    {"katana", "0.2.17"},
    {"katana", "0.2.18"},
    {"lanes_barista", "0.1.0"},
    {"lasp", "0.10.0"},
    {"libhowl", "0.1.31"},
    {"libsnarl", "0.3.40"},
    {"libsniffle", "0.3.37"},
    {"mc_eredis", "2.4.0"},
    {"mc_lhttpc", "4.1.0"},
    {"oc_google_reporter", "0.3.0"},
    {"oc_google_reporter", "0.4.0"},
    {"oox", "0.1.14"},
    {"oox", "0.1.15"},
    {"oox", "0.1.16"},
    {"oox", "0.1.17"},
    {"oox", "0.1.18"},
    {"oox", "0.1.19"},
    {"oox", "0.1.20"},
    {"oox", "0.1.21"},
    {"oox", "0.1.22"},
    {"oox", "0.1.23"},
    {"oox", "0.1.24"},
    {"oox", "0.1.25"},
    {"oox", "0.1.26"},
    {"oox", "0.1.27"},
    {"pe4kin", "0.2.0"},
    {"pe4kin", "0.2.1"},
    {"pe4kin", "0.2.2"},
    {"serverless", "0.4.2"},
    {"serverless", "0.4.3"},
    {"shotgun", "0.1.15"},
    {"shotgun", "0.2.3"},
    {"system_monitor", "0.3.0"},
    {"system_monitor", "1.0.1"},
    {"test_package", "1.0.0"},
    {"tirerl", "0.1.7"},
    {"tirerl", "0.1.8"},
    {"tirerl", "0.1.9"},
    {"trails", "0.1.1"},
    {"trails", "2.2.1"},
    {"trails", "2.3.0"},
    {"zotonic_core", "1.0.0-d0"},
    {"zotonic_core", "1.0.0-d1"},
    {"zotonic_filehandler", "1.0.0-d0"},
    {"zotonic_filehandler", "1.0.0-d1"},
    {"zotonic_fileindexer", "1.0.0-d0"},
    {"zotonic_filewatcher", "1.0.0-d0"},
    {"zotonic_launcher", "1.0.0-d1"},
    {"zotonic_listen_http", "1.0.0-d1"},
    {"zotonic_listen_mqtt", "1.0.0-d1"},
    {"zotonic_listen_smtp", "1.0.0-d1"},
    {"zotonic_mod_acl_mock", "1.0.0-d1"},
    {"zotonic_mod_acl_user_groups", "1.0.0-d1"},
    {"zotonic_mod_admin_category", "1.0.0-d1"},
    {"zotonic_mod_admin_config", "1.0.0-d1"},
    {"zotonic_mod_admin_frontend", "1.0.0-d1"},
    {"zotonic_mod_admin_identity", "1.0.0-d1"},
    {"zotonic_mod_admin_merge", "1.0.0-d1"},
    {"zotonic_mod_admin_modules", "1.0.0-d1"},
    {"zotonic_mod_admin_predicate", "1.0.0-d1"},
    {"zotonic_mod_admin_statistics", "1.0.0-d1"},
    {"zotonic_mod_admin", "1.0.0-d1"},
    {"zotonic_mod_artwork", "1.0.0-d1"},
    {"zotonic_mod_audio", "1.0.0-d1"},
    {"zotonic_mod_auth2fa", "1.0.0-d1"},
    {"zotonic_mod_authentication", "1.0.0-d1"},
    {"zotonic_mod_backup", "1.0.0-d1"},
    {"zotonic_mod_base", "1.0.0-d1"},
    {"zotonic_mod_bootstrap", "1.0.0-d1"},
    {"zotonic_mod_clamav", "1.0.0-d1"},
    {"zotonic_mod_comment", "1.0.0-d1"},
    {"zotonic_mod_contact", "1.0.0-d1"},
    {"zotonic_mod_content_groups", "1.0.0-d1"},
    {"zotonic_mod_cron", "1.0.0-d1"},
    {"zotonic_mod_custom_redirect", "1.0.0-d1"},
    {"zotonic_mod_development", "1.0.0-d1"},
    {"zotonic_mod_editor_tinymce", "1.0.0-d1"},
    {"zotonic_mod_email_dkim", "1.0.0-d1"},
    {"zotonic_mod_email_receive", "1.0.0-d1"},
    {"zotonic_mod_email_relay", "1.0.0-d1"},
    {"zotonic_mod_email_status", "1.0.0-d1"},
    {"zotonic_mod_export", "1.0.0-d1"},
    {"zotonic_mod_facebook", "1.0.0-d1"},
    {"zotonic_mod_filestore", "1.0.0-d1"},
    {"zotonic_mod_fileuploader", "1.0.0-d1"},
    {"zotonic_mod_geoip", "1.0.0-d1"},
    {"zotonic_mod_image_edit", "1.0.0-d1"},
    {"zotonic_mod_import_csv", "1.0.0-d1"},
    {"zotonic_mod_l10n", "1.0.0-d1"},
    {"zotonic_mod_linkedin", "1.0.0-d1"},
    {"zotonic_mod_logging", "1.0.0-d1"},
    {"zotonic_mod_mailinglist", "1.0.0-d1"},
    {"zotonic_mod_media_exif", "1.0.0-d1"},
    {"zotonic_mod_menu", "1.0.0-d1"},
    {"zotonic_mod_microsoft", "1.0.0-d1"},
    {"zotonic_mod_mqtt", "1.0.0-d1"},
    {"zotonic_mod_oauth2", "1.0.0-d1"},
    {"zotonic_mod_oembed", "1.0.0-d1"},
    {"zotonic_mod_ratelimit", "1.0.0-d1"},
    {"zotonic_mod_search", "1.0.0-d1"},
    {"zotonic_mod_seo_sitemap", "1.0.0-d1"},
    {"zotonic_mod_seo", "1.0.0-d1"},
    {"zotonic_mod_server_storage", "1.0.0-d1"},
    {"zotonic_mod_signup", "1.0.0-d1"},
    {"zotonic_mod_site_update", "1.0.0-d1"},
    {"zotonic_mod_ssl_ca", "1.0.0-d1"},
    {"zotonic_mod_ssl_letsencrypt", "1.0.0-d1"},
    {"zotonic_mod_survey", "1.0.0-d1"},
    {"zotonic_mod_syslog", "1.0.0-d1"},
    {"zotonic_mod_tkvstore", "1.0.0-d1"},
    {"zotonic_mod_translation", "1.0.0-d1"},
    {"zotonic_mod_twitter", "1.0.0-d1"},
    {"zotonic_mod_video_embed", "1.0.0-d1"},
    {"zotonic_mod_video", "1.0.0-d1"},
    {"zotonic_mod_zotonic_site_management", "1.0.0-d1"},
    {"zotonic_site_status", "1.0.0-d1"}
  ]

  @skip [
    "ami_models",
    "ami",
    "amqp_director",
    "broen",
    "bypass",
    "ejabberd",
    "kyu",
    "peluquero"
  ]

  @tag timeout: 120_000
  property "resolves releases" do
    load_registry()

    check all {package, version, dependencies} <- release() do
      Registry.put("$root", "1.0.0", dependencies)

      cond do
        package in @skip ->
          :ok

        {package, version} in @expected_failures ->
          assert {:error, _} = Resolver.run(Registry, %{}, MapSet.new())

        true ->
          # assert {:ok, _} = Resolver.run(Registry, %{}, MapSet.new())
          case Resolver.run(Registry, %{}, MapSet.new()) do
            {:ok, _} -> :ok
            {:error, _} -> IO.puts("{#{inspect(package)}, #{inspect(version)}},")
          end
      end
    end
  end
end
